In [1]:
# --- 자동 모듈 리로드 설정 ---
%load_ext autoreload
# %autoreload 2: 모든 모듈을 매번 자동으로 다시 로드
%autoreload 2

## 임포트

In [4]:
# --- 공통 라이브러리 import ---
import sys
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sys.path.append(r"D:\OneDrive - HKNC\@ Project_CQMS\# Workstation_2")

from _00_database.db_client import get_client
from _02_preprocessing.CQMS import df_4m_change as repo
from _02_preprocessing.HOPE import df_oeapp
from _02_preprocessing import helper_pandas
from _03_visualization import bi_301_OE_Quality_Issue_Dashboard as viz
from _05_commons import config

In [9]:
df = repo.filtered_4m_by_weekly(config.a_week_ago, config.today)
df['DOC_NO'] = df['DOC_NO'].str.replace('MANA-DOC', '4M-', regex=False)
df

# df.columns

,DOC_NO,PLANT,PURPOSE,SUBJECT,STATUS,REQUESTER,REG_DATE,COMP_DATE,URL,M_CODE
0,4M--2023-00021,DP,Cost reduction,Curing Productivity Improvement,NaN,21200031,2023-06-19,2023-07-07,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1025544
1,4M--2023-00020,IP,Nonconformity Improvement,Additional SNI and UTQG marking for OE Honda N...,NaN,60002485,2023-06-08,2023-07-13,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1025593
2,4M--2023-00023,KP,Cost reduction,OE RR 적정화 및 가류 생산성 향상,NaN,21400008,2023-06-19,2023-07-07,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1025144
3,4M--2023-00024,TP,Nonconformity Improvement,"Honda HR-V 17in AUS, BKB 부적합 개선을 위한 Spec.변경 요청",NaN,21000092,2023-06-21,2023-06-27,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1025718
4,4M--2023-00030,KP,Nonconformity Improvement,235/55R19H RA33Y AUS 발생에 따른 개선 Spec 적용 요청,NaN,21500066,2023-07-04,2023-08-02,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1028034
...,...,...,...,...,...,...,...,...,...,...
699,4M--2024-00212,CP,Performance Improvement,Approval for 7 Sizes New Customize Bladder in ...,NaN,81202522,2024-12-05,2024-12-13,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1025303
700,4M--2024-00198,MP,Nonconformity Improvement,BSH prevent KT1027039 VW ID Buzz,NaN,70810877,2024-11-20,2024-11-21,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1027027
701,4M--2025-00003,DP,Nonconformity Improvement,225/45R17W 04 H436 N _ HMC(CN7_HEV) _Nonconfor...,NaN,21600202,2025-01-07,2025-02-03,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1024034
702,4M--2024-00089,JP,Performance Improvement,가흥공장 Groove crack 발생품 개선,NaN,21602363,2024-06-12,2025-01-16,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1028485
703,4M--2024-00017,KP,Cost reduction,Cost Reduction,NaN,20700204,2024-01-31,2024-05-20,http://egqms.hankooktech.com/CHANGE_MANAGE_FOU...,1029348

## 변수

In [92]:
year = 2025
start_date = config.a_week_ago
end_date = config.today

In [93]:
df = df_quality_issue.load_quality_issues_for_3_years(year)
display(df.head())
print(df.shape)
print(df.info())

,OEQ GROUP,PLANT,STAGE,OEM,VEH,PJT,ISSUE_ETC,DESCRIPTION,CAUSE_OF_DEFECT,OWNER_ID,...,CAT,SUB_CAT,URL,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,MTTC,YYYY,MM
DOC_NO,,,,,,,,,,,,,,,,,,,,,
QI-2023-00072,China OE Quality,JP,02,Toyota,Camry,015B,UST（Uneven sectional in Tread ）,1 resident staff and 2 JP QA staff conduct ful...,Curing equipment failure,81102484,...,Deform,Tread,http://egqms.hankooktech.com/OE_Quality_Issue/...,14,<NA>,-1,1,14,2023,7
QI-2024-00020,China OE Quality,CP,02,Ford,Mondeo,CD542 4DR,The shoulder of the tire is abnormal and lacks...,1. Location: Chang an Ford 2nd Line.\r\n2. Cha...,根据返回轮胎外观状态和制造过程追踪分析，确定为外物剐蹭造成损伤,81102484,...,Deform,Sidewall,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,8,5,5,10,2024,2
QI-2024-00113,China OE Quality,CP,02,Ford,Mondeo,CD542 4DR,胎侧表面起皮\r\nTire sidewall surface peeling.,1.已经安排人员去Ford工厂及装胎厂sorting。\r\nPersonnel have ...,起皮物质是修饰液，该物质为常规使用且经过验证，对轮胎性能无影响。\r\n发生原因为喷涂量过多造成,81102484,...,Deform,Sidewall,http://egqms.hankooktech.com/OE_Quality_Issue/...,1,<NA>,7,4,12,2024,8
QI-2025-00070,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,FAW-VW reports that 29 unsold Magotan B8L new ...,Return analysis after tire replacement,None,81102484,...,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,7,4,<NA>,4,2025,4
QI-2025-00066,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,81102484,...,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4

(166, 36)
<class 'pandas.core.frame.DataFrame'>
Index: 166 entries, QI-2023-00072 to QI-2024-00033
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OEQ GROUP        166 non-null    category
 1   PLANT            166 non-null    category
 2   STAGE            166 non-null    object
 3   OEM              166 non-null    category
 4   VEH              166 non-null    object
 5   PJT              166 non-null    object
 6   ISSUE_ETC        166 non-null    object
 7   DESCRIPTION      166 non-null    object
 8   CAUSE_OF_DEFECT  159 non-null    object
 9   OWNER_ID         165 non-null    object
 10  RESP_ID          166 non-null    object
 11  OCC_DATE         166 non-null    datetime64[ns]
 12  REG_DATE         166 non-null    datetime64[ns]
 13  RETURN_YN        166 non-null    object
 14  RTN_DATE         72 non-null     datetime64[ns]
 15  CTM_DATE         158 non-null    datetime64[ns]
 16  HK_FAULT_YN      159 non-null    object
 17  COMP_DATE        159 non-null    datetime64[ns]
 18  STATUS           166 non-null    category
 19  LOCATION         166 non-null    category
 20  KPI              166 non-null    object
 21  MARKET           166 non-null    category
 22  SEQ              166 non-null    object
 23  M_CODE           166 non-null    object
 24  PNL_NM           148 non-null    object
 25  TYPE             166 non-null    category
 26  CAT              166 non-null    object
 27  SUB_CAT          166 non-null    object
 28  URL              166 non-null    object
 29  REG_PRD          166 non-null    Int64
 30  RTN_PRD          74 non-null     Int64
 31  CTM_PRD          164 non-null    Int64
 32  COMP_PRD         158 non-null    Int64
 33  MTTC             166 non-null    Int64
 34  YYYY             166 non-null    int32
 35  MM               166 non-null    int32
dtypes: Int64(5), category(7), datetime64[ns](5), int32(2), object(17)
memory usage: 41.6+ KB
None

In [94]:
df = df_quality_issue.load_sellin_data_for_3_years(year)
display(df.head())
print(df.shape)
print(df.info())

  PLANT  YYYY  MM  SUPP_QTY
0    CP  2023   1    156086
1    CP  2023   2    278924
2    CP  2023   3    328668
3    CP  2023   4    278657
4    CP  2023   5    300373

(261, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   PLANT     261 non-null    object
 1   YYYY      261 non-null    int64
 2   MM        261 non-null    int64
 3   SUPP_QTY  261 non-null    int64
dtypes: int64(3), object(1)
memory usage: 8.3+ KB
None

In [95]:
df = df_quality_issue.load_sellin_by_ev(year)
display(df.head())
print(df.shape)
print(df.info())

  EV  SUPP_QTY
0  N    553008
1  Y     91621

(2, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   EV        2 non-null      object
 1   SUPP_QTY  2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes
None

In [96]:
df = df_quality_issue.load_quality_issues_by_week(start_date, end_date)
display(df.head())
print(df.shape)
print(df.info())

,OEQ GROUP,PLANT,STAGE,OEM,VEH,PJT,ISSUE_ETC,DESCRIPTION,CAUSE_OF_DEFECT,OWNER_ID,...,SUB_CAT,URL,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,MTTC,YYYY,MM,Status
DOC_NO,,,,,,,,,,,,,,,,,,,,,
QI-2023-00078,China OE Quality,JP,02,Toyota,Corolla,115D,Reverse marking.\r\nRight：Marking in DOT side\...,"1. On July 17, the resident staff went to the ...",Equipment failure. The turning cylinder was st...,81102484,...,DB marking,http://egqms.hankooktech.com/OE_Quality_Issue/...,2,<NA>,4,1,7,2023,7,NaN
QI-2023-00116,China OE Quality,JP,02,Toyota,Corolla,115D,The Assembly plant found a 115D tire without y...,For this tire ，Resident staff business travel...,The D/B yellow marking position is in the tire...,81102484,...,DB marking,http://egqms.hankooktech.com/OE_Quality_Issue/...,119,<NA>,-1,0,118,2023,10,NaN
QI-2024-00010,China OE Quality,JP,02,VW,T-Cross,VW216,S/W bulge.\r\nLE (Local Engineer in Spain(Aug...,Sorting of tires in Eurofit Assembly plant by ...,轮胎为外部损伤导致,81102484,...,BPS(Dent/Bulge),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,5,9,1,10,2024,1,NaN
QI-2024-00007,China OE Quality,CP,02,Ford,Mondeo,CD542 4DR,FORD 2 plant maintenance area found 1 tire wit...,Replacement of assembly tires,该模具生产时OF发生，未刮除干净，发送到OEM\r\nWhen the mold is pr...,81102484,...,Flash,http://egqms.hankooktech.com/OE_Quality_Issue/...,11,<NA>,1,1,13,2024,1,NaN
QI-2024-00020,China OE Quality,CP,02,Ford,Mondeo,CD542 4DR,The shoulder of the tire is abnormal and lacks...,1. Location: Chang an Ford 2nd Line.\r\n2. Cha...,根据返回轮胎外观状态和制造过程追踪分析，确定为外物剐蹭造成损伤,81102484,...,Sidewall,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,8,5,5,10,2024,2,NaN

(300, 37)
<class 'pandas.core.frame.DataFrame'>
Index: 300 entries, QI-2023-00078 to QI-2024-00137
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OEQ GROUP        300 non-null    category
 1   PLANT            300 non-null    category
 2   STAGE            300 non-null    object
 3   OEM              300 non-null    category
 4   VEH              300 non-null    object
 5   PJT              293 non-null    object
 6   ISSUE_ETC        300 non-null    object
 7   DESCRIPTION      299 non-null    object
 8   CAUSE_OF_DEFECT  282 non-null    object
 9   OWNER_ID         297 non-null    object
 10  RESP_ID          299 non-null    object
 11  OCC_DATE         300 non-null    datetime64[ns]
 12  REG_DATE         300 non-null    datetime64[ns]
 13  RETURN_YN        300 non-null    object
 14  RTN_DATE         125 non-null    datetime64[ns]
 15  CTM_DATE         290 non-null    datetime64[ns]
 16  HK_FAULT_YN      290 non-null    object
 17  COMP_DATE        290 non-null    datetime64[ns]
 18  STATUS           300 non-null    category
 19  LOCATION         300 non-null    category
 20  KPI              300 non-null    object
 21  MARKET           299 non-null    category
 22  SEQ              300 non-null    object
 23  M_CODE           300 non-null    object
 24  PNL_NM           269 non-null    object
 25  TYPE             300 non-null    category
 26  CAT              300 non-null    object
 27  SUB_CAT          300 non-null    object
 28  URL              300 non-null    object
 29  REG_PRD          300 non-null    Int64
 30  RTN_PRD          129 non-null    Int64
 31  CTM_PRD          296 non-null    Int64
 32  COMP_PRD         290 non-null    Int64
 33  MTTC             300 non-null    Int64
 34  YYYY             300 non-null    int32
 35  MM               300 non-null    int32
 36  Status           10 non-null     category
dtypes: Int64(5), category(8), datetime64[ns](5), int32(2), object(17)
memory usage: 82.2+ KB
None

In [97]:
df = df_quality_issue.load_ongoing_quality_issues()
display(df.head())
print(df.shape)
print(df.info())

,DOC_NO,OEQ GROUP,PLANT,STAGE,OEM,VEH,PJT,ISSUE_ETC,DESCRIPTION,CAUSE_OF_DEFECT,...,LOCATION,KPI,MARKET,SEQ,M_CODE,PNL_NM,TYPE,CAT,SUB_CAT,URL
180,QI-2025-00039,Europe OE Quality,MP,02,VW,ID.4,VW316/6EU_B,"After the delivery of the Volkswagen ID.4, vib...",Trackback production and quality records.,"The Curing Bladder was coated ,it caused the n...",...,Non-official(In-line),Exclude,ASIA(Korea),2E8FC53B6682D646E0633C071FCAD1CB,1028977,Peninger Szabolcs,Apperance,Vibration,Field,http://egqms.hankooktech.com/OE_Quality_Issue/...
20,QI-2025-00066,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,...,Field,Include,ASIA(China),1963da0906b1fbab73745d35101173d5,1028484,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...
21,QI-2025-00067,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,...,Field,Include,ASIA(China),1963daa2ccdfe833e6c19fd3f4f21ec9,1028485,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...
23,QI-2025-00065,China OE Quality,JP,02,VW,Bora,BORA MQB PA,"According to the notification from FAW-VW, the...",Goodwill implementation.,None,...,Field,Include,ASIA(China),1963d990386b883dc67ffb54b4b31264,1027785,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...
24,QI-2025-00064,China OE Quality,CP,02,VW,Jetta,NCS NF PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,...,Field,Include,ASIA(China),1963d884cf03c9b218d93d9818f5dd60,1032614,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...

(10, 33)
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 180 to 91
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DOC_NO           10 non-null     object
 1   OEQ GROUP        10 non-null     object
 2   PLANT            10 non-null     object
 3   STAGE            10 non-null     object
 4   OEM              10 non-null     object
 5   VEH              10 non-null     object
 6   PJT              9 non-null      object
 7   ISSUE_ETC        10 non-null     object
 8   DESCRIPTION      10 non-null     object
 9   CAUSE_OF_DEFECT  4 non-null      object
 10  TYPE_CD          10 non-null     object
 11  CAT_CD           10 non-null     object
 12  SUB_CAT_CD       10 non-null     object
 13  OWNER_ID         10 non-null     object
 14  RESP_ID          10 non-null     object
 15  OCC_DATE         10 non-null     object
 16  REG_DATE         10 non-null     datetime64[ns]
 17  RETURN_YN        10 non-null     object
 18  RTN_DATE         8 non-null      object
 19  CTM_DATE         1 non-null      object
 20  HK_FAULT_YN      0 non-null      object
 21  COMP_DATE        0 non-null      object
 22  STATUS           10 non-null     object
 23  LOCATION         10 non-null     object
 24  KPI              10 non-null     object
 25  MARKET           10 non-null     object
 26  SEQ              10 non-null     object
 27  M_CODE           10 non-null     object
 28  PNL_NM           9 non-null      object
 29  TYPE             10 non-null     object
 30  CAT              10 non-null     object
 31  SUB_CAT          10 non-null     object
 32  URL              10 non-null     object
dtypes: datetime64[ns](1), object(32)
memory usage: 2.7+ KB
None

In [98]:
df = df_quality_issue.summarize_ongoing_quality_by_plant()
display(df.head())
print(df.shape)
print(df.info())

       count
PLANT
JP         6
CP         1
KP         1
MP         1
TP         1

(5, 1)
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, JP to TP
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   count   5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes
None

In [99]:
df = df_quality_issue.summarize_ongoing_quality_by_month()
display(df.head())
print(df.shape)
print(df.info())

            count
REG_DATE
2025-02-28      1
2025-03-31      0
2025-04-30      6
2025-05-31      3

(4, 1)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4 entries, 2025-02-28 to 2025-05-31
Freq: ME
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   count   4 non-null      int64
dtypes: int64(1)
memory usage: 64.0 bytes
None

In [100]:
df = df_quality_issue.aggregate_oeqi_by_plant_monthly(year)
display(df)
print(df.shape)
print(df.info())

     YYYY  MM PLANT  count  SUPP_QTY  count_cumsum  SUPP_QTY_cumsum  OEQI
0    2023   1    CP      0  156086.0             0         156086.0   0.0
1    2023   1    DP      0  177674.0             0         177674.0   0.0
2    2023   1    HP      0  160792.0             0         160792.0   0.0
3    2023   1    IP      0   78782.0             0          78782.0   0.0
4    2023   1    JP      0  406405.0             0         406405.0   0.0
..    ...  ..   ...    ...       ...           ...              ...   ...
319  2025  12    JP      0       NaN             6              NaN   NaN
320  2025  12    KP      0       NaN             2              NaN   NaN
321  2025  12    MP      0       NaN             5              NaN   NaN
322  2025  12    OT      0       NaN             0              NaN   NaN
323  2025  12    TP      0       NaN             7              NaN   NaN

[324 rows x 8 columns]

(324, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YYYY             324 non-null    int32
 1   MM               324 non-null    int32
 2   PLANT            324 non-null    object
 3   count            324 non-null    int64
 4   SUPP_QTY         261 non-null    float64
 5   count_cumsum     324 non-null    int64
 6   SUPP_QTY_cumsum  261 non-null    float64
 7   OEQI             261 non-null    float64
dtypes: float64(3), int32(2), int64(2), object(1)
memory usage: 17.8+ KB
None

In [101]:
df = df_quality_issue.aggregate_oeqi_by_plant_yearly(year)
display(df)
print(df.shape)
print(df.info())

,PLANT,YYYY,count,MTTC,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,SUPP_QTY,OEQI
0,CP,2025,1,17.0,0.0,0.0,17.0,<NA>,794151,1.259206
1,DP,2025,0,<NA>,<NA>,<NA>,<NA>,<NA>,1082003,0.000000
2,HP,2025,1,8.0,1.0,<NA>,5.0,2.0,1093200,0.914746
3,IP,2025,1,42.0,21.0,0.0,11.0,10.0,1439734,0.694573
4,JP,2025,6,13.833333,0.166667,1.166667,13.5,1.0,4356531,1.377243
5,KP,2025,2,15.5,2.0,0.0,12.0,1.5,2582645,0.774400
6,MP,2025,5,7.0,0.0,3.0,5.4,1.6,4813177,1.038815
7,OT,2025,0,<NA>,<NA>,<NA>,<NA>,<NA>,105176,0.000000
8,TP,2025,7,19.142857,1.285714,-1.0,14.142857,4.333333,1671388,4.188136

(9, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   PLANT     9 non-null      object
 1   YYYY      9 non-null      int32
 2   count     9 non-null      int64
 3   MTTC      7 non-null      Float64
 4   REG_PRD   7 non-null      Float64
 5   RTN_PRD   6 non-null      Float64
 6   CTM_PRD   7 non-null      Float64
 7   COMP_PRD  6 non-null      Float64
 8   SUPP_QTY  9 non-null      int64
 9   OEQI      9 non-null      float64
dtypes: Float64(5), float64(1), int32(1), int64(2), object(1)
memory usage: 861.0+ bytes
None

In [102]:
df = df_quality_issue.aggregate_oeqi_by_global_monthly(year)
display(df)
print(df.shape)
print(df.info())

    YYYY  MM  count  SUPP_QTY  count_cumsum  SUPP_QTY_cumsum      OEQI
0   2023   1    9.0   1893620           9.0          1893620  4.752802
1   2023   2   13.0   4018738          22.0          5912358  3.721020
2   2023   3    3.0   4562090          25.0         10474448  2.386761
3   2023   4    3.0   4299805          28.0         14774253  1.895189
4   2023   5    2.0   4592590          30.0         19366843  1.549039
5   2023   6    7.0   4622136          37.0         23988979  1.542375
6   2023   7   11.0   4054802          48.0         28043781  1.711609
7   2023   8    1.0   3981854          49.0         32025635  1.530024
8   2023   9    6.0   4223770          55.0         36249405  1.517266
9   2023  10   15.0   4578216          70.0         40827621  1.714526
10  2023  11    5.0   4646772          75.0         45474393  1.649280
11  2023  12    2.0   4023567          77.0         49497960  1.555620
12  2024   1    9.0   4296866           9.0          4296866  2.094550
13  2024   2    5.0   3935941          14.0          8232807  1.700514
14  2024   3    5.0   4296526          19.0         12529333  1.516441
15  2024   4    7.0   4467841          26.0         16997174  1.529666
16  2024   5    8.0   4023711          34.0         21020885  1.617439
17  2024   6    9.0   3948626          43.0         24969511  1.722100
18  2024   7    4.0   3532338          47.0         28501849  1.649016
19  2024   8    6.0   3851753          53.0         32353602  1.638148
20  2024   9    6.0   4354027          59.0         36707629  1.607295
21  2024  10    4.0   4653027          63.0         41360656  1.523187
22  2024  11    3.0   4535262          66.0         45895918  1.438036
23  2024  12    0.0   3879334          66.0         49775252  1.325960
24  2025   1    5.0   3935159           5.0          3935159  1.270597
25  2025   2    5.0   3957267          10.0          7892426  1.267038
26  2025   3    5.0   4588457          15.0         12480883  1.201838
27  2025   4    7.0   4530697          22.0         17011580  1.293237
28  2025   5    1.0    926425          23.0         17938005  1.282194

(29, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YYYY             29 non-null     int64
 1   MM               29 non-null     int64
 2   count            29 non-null     float64
 3   SUPP_QTY         29 non-null     int64
 4   count_cumsum     29 non-null     float64
 5   SUPP_QTY_cumsum  29 non-null     int64
 6   OEQI             29 non-null     float64
dtypes: float64(3), int64(4)
memory usage: 1.7 KB
None

In [103]:
df = df_quality_issue.aggregate_oeqi_by_global_yearly(year)
display(df)
print(df.shape)
print(df.info())

,YYYY,count,MTTC,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,SUPP_QTY,OEQI
0,2023,77,45.545455,21.987013,39.962963,20.173333,3.960526,49497960,1.555620
1,2024,66,21.166667,3.772727,3.4,12.848485,4.545455,49775252,1.325960
2,2025,23,15.217391,1.565217,1.0,11.478261,3.125,17938005,1.282194

(3, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   YYYY      3 non-null      int32
 1   count     3 non-null      int64
 2   MTTC      3 non-null      Float64
 3   REG_PRD   3 non-null      Float64
 4   RTN_PRD   3 non-null      Float64
 5   CTM_PRD   3 non-null      Float64
 6   COMP_PRD  3 non-null      Float64
 7   SUPP_QTY  3 non-null      int64
 8   OEQI      3 non-null      float64
dtypes: Float64(5), float64(1), int32(1), int64(2)
memory usage: 351.0 bytes
None

In [104]:
df = df_quality_issue.aggregate_oeqi_by_goeq_monthly(year)
display(df)
print(df.shape)
print(df.info())

            OEQ GROUP  MM  count  cum_count  SUPP_QTY  CUM_SUPP_QTY      OEQI
10       G.OE Quality   1      1          1   1158171       1158171  0.863430
11       G.OE Quality   2      1          2   1266475       2424646  0.824863
12       G.OE Quality   3      0          2   1269143       3693789  0.541449
13       G.OE Quality   4      1          3   1188984       4882773  0.614405
14       G.OE Quality   5      0          3    221609       5104382  0.587730
0    China OE Quality   1      1          1   1400009       1400009  0.714281
1    China OE Quality   2      1          2   1237686       2637695  0.758238
2    China OE Quality   3      0          2   1551065       4188760  0.477468
3    China OE Quality   4      5          7   1702442       5891202  1.188213
4    China OE Quality   5      1          8    352680       6243882  1.281254
5   Europe OE Quality   1      3          3   1018147       1018147  2.946529
6   Europe OE Quality   2      1          4   1068584       2086731  1.916874
7   Europe OE Quality   3      1          5   1268525       3355256  1.490199
8   Europe OE Quality   4      0          5   1197618       4552874  1.098207
9   Europe OE Quality   5      0          5    260303       4813177  1.038815
15      NA OE Quality   1      0          0    339642        339642  0.000000
16      NA OE Quality   2      2          2    358080        697722  2.866471
17      NA OE Quality   3      4          6    474886       1172608  5.116799
18      NA OE Quality   4      1          7    410863       1583471  4.420668
19      NA OE Quality   5      0          7     87917       1671388  4.188136

(20, 7)
<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 10 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OEQ GROUP     20 non-null     category
 1   MM            20 non-null     int32
 2   count         20 non-null     int64
 3   cum_count     20 non-null     int64
 4   SUPP_QTY      20 non-null     int64
 5   CUM_SUPP_QTY  20 non-null     int64
 6   OEQI          20 non-null     float64
dtypes: category(1), float64(1), int32(1), int64(4)
memory usage: 1.2 KB
None

In [105]:
df = df_quality_issue.aggregate_oeqi_by_goeq_yearly(year)
display(df)
print(df.shape)
print(df.info())

           OEQ GROUP  count       MTTC   REG_PRD  RTN_PRD    CTM_PRD  COMP_PRD
0       G.OE Quality      3  24.333333  8.333333      0.0  11.666667  4.333333
1   China OE Quality      8       13.5      0.25      1.0     12.875       1.5
2  Europe OE Quality      5        7.0       0.0      3.0        5.4       1.6
3      NA OE Quality      7  19.142857  1.285714     -1.0  14.142857  4.333333

(4, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OEQ GROUP  4 non-null      category
 1   count      4 non-null      int64
 2   MTTC       4 non-null      Float64
 3   REG_PRD    4 non-null      Float64
 4   RTN_PRD    4 non-null      Float64
 5   CTM_PRD    4 non-null      Float64
 6   COMP_PRD   4 non-null      Float64
dtypes: Float64(5), category(1), int64(1)
memory usage: 552.0 bytes
None

In [106]:
dfs = df_quality_issue.compare_quality_by_ev_group(year)
for df in dfs:
    display(df)
    print(df.shape)
    print(df.info())

,OEQ GROUP,PLANT,STAGE,OEM,VEH,PJT,ISSUE_ETC,DESCRIPTION,CAUSE_OF_DEFECT,OWNER_ID,...,SUB_CAT,URL,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,MTTC,YYYY,MM,EV
DOC_NO,,,,,,,,,,,,,,,,,,,,,
QI-2025-00070,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,FAW-VW reports that 29 unsold Magotan B8L new ...,Return analysis after tire replacement,None,81102484,...,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,7,4,<NA>,4,2025,4,N
QI-2025-00066,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,81102484,...,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4,N
QI-2025-00067,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,81102484,...,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4,N
QI-2025-00040,China OE Quality,JP,02,VW,Tayron,A SUV PA,FAW-VW feedback that there have been 13 inci...,Analyze the returned tires\r\n,Considering the market sales environment and c...,81102484,...,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,1,0,22,1,24,2025,2,N
QI-2025-00065,China OE Quality,JP,02,VW,Bora,BORA MQB PA,"According to the notification from FAW-VW, the...",Goodwill implementation.,None,81102484,...,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4,N
QI-2025-00064,China OE Quality,CP,02,VW,Jetta,NCS NF PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,81102484,...,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4,N
QI-2025-00072,China OE Quality,JP,02,Leapmotor,C11,C11,"接技术服务T反馈,零跑售后投诉胎侧凹坑,邀请返回分析 Receiving feedback...",返回分析 Return to analysis,G/T着地或硫化下模具污染导致，硫化G/T投入前异物检查，设备停机再稼动模具清扫、卫生确认.,80021227,...,FM(Foreign Material),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,4,<NA>,4,2025,5,Y
QI-2025-00006,China OE Quality,HP,02,Ford,F-Series,P558,Parts tires arrived to CLI with large sticker...,"Planned to retrive tires in trailer, but sent ...",TBR tires shipped to OHAP has label attached o...,81203449,...,Etc,http://egqms.hankooktech.com/OE_Quality_Issue/...,1,<NA>,5,2,8,2025,1,N
QI-2025-00030,G.OE Quality,KP,02,VW,Jetta,VW371 GLI PA,1. Found DM assumed tire in ALO warehouse in M...,"1, Meeting with VW to discuss how to deal with...","인위적인 상황 평가시 Mold 청소 후 차이로 인한 원인 추정\r\n관련 고속, 내...",21400100,...,Dirty Mold(DM),http://egqms.hankooktech.com/OE_Quality_Issue/...,2,<NA>,7,1,10,2025,2,N
QI-2025-00058,G.OE Quality,KP,02,GM,Trailblazer,9BYC,1) 이슈현상 : GMK Trailblazer 차량에 공급되는 타이어 사양 점검시 ...,1) Korea OE2팀 최규현님 최초이슈 접수 (From GMK 신대진차장) : ...,Mold - Container - 가류기 설비 공차로 인하여 Side 판 틀어짐 발생,20800091,...,Etc,http://egqms.hankooktech.com/OE_Quality_Issue/...,2,0,17,2,21,2025,4,N
QI-2025-00015,Europe OE Quality,MP,02,VW,Enyaq,SK316/5EU,Skoda claimed at Mlada Boleslav Czech Rep. pro...,Production / quality & shipping history after ...,OF was not detected by the visual inspector. T...,70700077,...,Flash,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,6,1,1,2,2025,1,Y
QI-2025-00043,Europe OE Quality,MP,02,Renault-Nissan,Juke,P13A,Trim and Chassis department highlighted 1 EA R...,Trace back shipping history and check the mark...,The marking on the tire was handled incorrectly.,70700077,...,Red-Dot ( IDR ),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,<NA>,2,3,5,2025,2,N
QI-2025-00009,Europe OE Quality,MP,02,Renault-Nissan,Juke,P13A,Nissan Sunderland plant during the inspection ...,Check the production / quality history.,The marking on the tire was handled incorrectly.,70700077,...,Red-Dot ( IDR ),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,<NA>,8,1,9,2025,1,N
QI-2025-00008,Europe OE Quality,MP,02,VW,T-Roc,VW276,Conti Lemmerz has found tires with Bulge NCF a...,Stock revision / production & quality history....,Tires are claimed by Bulge during mounting tir...,70700077,...,BPS(Dent/Bulge),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,10,1,11,2025,1,N
QI-2025-00054,Europe OE Quality,MP,02,VW,Kodiaq,SK336/1,At skoda side claimed a tire with Dirty mold n...,Check current production and the history ( qua...,The visual inspector inspected the tire during...,70700077,...,Dirty Mold(DM),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,<NA>,6,2,8,2025,3,N
QI-2025-00012,G.OE Quality,IP,02,Toyota,Bezza,D42L,There is pin hole pricking ( Air Leak ) at Sid...,Sample NG tire on progress analyze by QC team.,"""Wire visible on the sidewall but visual inspe...",60002485,...,Air Vent Hole,http://egqms.hankooktech.com/OE_Quality_Issue/...,21,0,11,10,42,2025,1,N
QI-2025-00044,NA OE Quality,TP,02,Toyota,Camry,380D,Loose bead flash became trapped between rim fl...,Notified QA inspectors of issue -> ensure no l...,Loose bead flash became trapped between rim fl...,40005602,...,Air Leak,http://egqms.hankooktech.com/OE_Quality_Issue/...,2,<NA>,21,2,25,2025,3,N
QI-2025-00057,NA OE Quality,TP,02,KMC,EV9,MVA,HMGMA received a delivery of 52931-XA510 from ...,Sorting the tires at the Hodges warehouse,Supplied from OE warehouse without distinction...,21000075,...,Mixing,http://egqms.hankooktech.com/OE_Quality_Issue/...,3,<NA>,2,0,5,2025,3,N
QI-2025-00049,NA OE Quality,TP,02,Tesla,Model Y,OPAL,Red dot some faded (SMEARED RED DOT ISSUE for ...,checking the process and have alerted our ship...,Some red-dot reworked tires have faded as they...,21000075,...,Red-Dot ( IDR ),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,<NA>,11,4,15,2025,3,Y
QI-2025-00018,NA OE Quality,TP,02,Honda,CR-V,3A0A,Honda found out the bulge after mounting the t...,Requested the barcode and checking the UF insp...,Improperly formed carcass splice causes a gap ...,21000075,...,BPS(Dent/Bulge),http://egqms.hankooktech.com/OE_Quality_Issue/...,1,<NA>,19,0,20,2025,2,N
QI-2025-00071,NA OE Quality,TP,02,Honda,CR-V,3A0A,Checking the manufacturing process to verify t...,Requested to sort tires at our 3rd party wareh...,Possible root cause : curing loader chuck adet...,21000075,...,FM(Foreign Material),http://egqms.hankooktech.com/OE_Quality_Issue/...,2,<NA>,7,<NA>,9,2025,4,N
QI-2025-00017,NA OE Quality,TP,02,Honda,HR-V,3W0A,Honda found out the FM tire,Checking the manufacturing history and shared...,DOT Plate 제거 후 처리 절차 미흡,21000075,...,FM(Foreign Material),http://egqms.hankooktech.com/OE_Quality_Issue/...,1,<NA>,27,-1,27,2025,2,N
QI-2025-00050,NA OE Quality,TP,02,Renault-Nissan,Frontier,H61P,Nissan found the sidewall issue during the mou...,Requested the barcode information and investig...,"Possible root cause : during vent drilling, a ...",21000075,...,Pin Hole ( Pin Hole,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,-1,12,21,33,2025,3,N

(23, 37)
<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, QI-2025-00070 to QI-2025-00050
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OEQ GROUP        23 non-null     category
 1   PLANT            23 non-null     category
 2   STAGE            23 non-null     object
 3   OEM              23 non-null     category
 4   VEH              23 non-null     object
 5   PJT              23 non-null     object
 6   ISSUE_ETC        23 non-null     object
 7   DESCRIPTION      23 non-null     object
 8   CAUSE_OF_DEFECT  18 non-null     object
 9   OWNER_ID         23 non-null     object
 10  RESP_ID          23 non-null     object
 11  OCC_DATE         23 non-null     datetime64[ns]
 12  REG_DATE         23 non-null     datetime64[ns]
 13  RETURN_YN        23 non-null     object
 14  RTN_DATE         12 non-null     datetime64[ns]
 15  CTM_DATE         16 non-null     datetime64[ns]
 16  HK_FAULT_YN      16 non-null     object
 17  COMP_DATE        16 non-null     datetime64[ns]
 18  STATUS           23 non-null     category
 19  LOCATION         23 non-null     category
 20  KPI              23 non-null     object
 21  MARKET           23 non-null     category
 22  SEQ              23 non-null     object
 23  M_CODE           23 non-null     object
 24  PNL_NM           17 non-null     object
 25  TYPE             23 non-null     category
 26  CAT              23 non-null     object
 27  SUB_CAT          23 non-null     object
 28  URL              23 non-null     object
 29  REG_PRD          23 non-null     Int64
 30  RTN_PRD          12 non-null     Int64
 31  CTM_PRD          23 non-null     Int64
 32  COMP_PRD         16 non-null     Int64
 33  MTTC             23 non-null     Int64
 34  YYYY             23 non-null     int32
 35  MM               23 non-null     int32
 36  EV               23 non-null     object
dtypes: Int64(5), category(7), datetime64[ns](5), int32(2), object(18)
memory usage: 8.3+ KB
None

  EV  cnt
0  N   20
1  Y    3

(2, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   EV      2 non-null      object
 1   cnt     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes
None

    cnt  SUPP_QTY       OEQI
EV
N    20    553008  36.165842
Y     3     91621  32.743585

(2, 3)
<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, N to Y
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cnt       2 non-null      int64
 1   SUPP_QTY  2 non-null      int64
 2   OEQI      2 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 64.0+ bytes
None

                SUB_CAT  cnt
0  FM(Foreign Material)    1
1                 Flash    1
2       Red-Dot ( IDR )    1

(3, 2)
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SUB_CAT  3 non-null      object
 1   cnt      3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 72.0+ bytes
None

                SUB_CAT  cnt
6          Groove Crack    6
2       BPS(Dent/Bulge)    2
5  FM(Foreign Material)    2
9       Red-Dot ( IDR )    2
3        Dirty Mold(DM)    2
1         Air Vent Hole    1
0              Air Leak    1

(7, 2)
<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 6 to 0
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SUB_CAT  7 non-null      object
 1   cnt      7 non-null      int64
dtypes: int64(1), object(1)
memory usage: 168.0+ bytes
None

In [107]:
df = df_quality_issue.pivot_quality_by_week_and_status(start_date, end_date)
display(df)
print(df.shape)
print(df.info())

Status   PLANT  Open  Open & Close  Close  On-going
0           DP     0             0      0         0
1           KP     1             0      0         0
2           JP     2             0      0         4
3           HP     0             0      0         0
4           CP     0             0      0         1
5           MP     0             0      0         1
6           IP     0             0      0         0
7           TP     0             0      0         1
8       Global     3             0      0         7

(9, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PLANT         9 non-null      object
 1   Open          9 non-null      int64
 2   Open & Close  9 non-null      int64
 3   Close         9 non-null      int64
 4   On-going      9 non-null      int64
dtypes: int64(4), object(1)
memory usage: 492.0+ bytes
None

# 나중에 확인할 함수

In [108]:
sqlite_query = """--sql
SELECT * 
FROM sellin_monthly_agg
"""
df_sellin = get_client('sqlite').execute(sqlite_query)
df_sellin = helper_pandas.standardize_columns_uppercase(df_sellin)
df_sellin = df_sellin[df_sellin['RE/OE'] == 'OE']
df_sellin[['YYYY', 'MM']] = df_sellin[['YYYY', 'MM']].astype('int')

df_app = df_oeapp.load_oeapp_df()
df_app = helper_pandas.standardize_columns_uppercase(df_app)

merge_df = pd.merge(df_sellin, df_app[["PLANT", "M_CODE"]], how='left', on = 'M_CODE')
merge_df = merge_df.groupby(['PLANT', 'YYYY', 'MM'], observed = False)['SUPP_QTY'].sum().reset_index()

In [109]:
display(merge_df)
print(merge_df.shape)
print(merge_df.info())

    PLANT  YYYY  MM  SUPP_QTY
0      CP  2023   1    176668
1      CP  2023   2    309726
2      CP  2023   3    367213
3      CP  2023   4    294761
4      CP  2023   5    350197
..    ...   ...  ..       ...
256    TP  2025   1    359628
257    TP  2025   2    378092
258    TP  2025   3    494334
259    TP  2025   4    427483
260    TP  2025   5     92227

[261 rows x 4 columns]

(261, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   PLANT     261 non-null    object
 1   YYYY      261 non-null    int64
 2   MM        261 non-null    int64
 3   SUPP_QTY  261 non-null    int64
dtypes: int64(3), object(1)
memory usage: 8.3+ KB
None

In [110]:
df = df_quality_issue.load_sellin_data_for_3_years(year)
print(df.shape)
print(df.info())

(261, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   PLANT     261 non-null    object
 1   YYYY      261 non-null    int64
 2   MM        261 non-null    int64
 3   SUPP_QTY  261 non-null    int64
dtypes: int64(3), object(1)
memory usage: 8.3+ KB
None

In [111]:
df = df_quality_issue.aggregate_oeqi_by_plant_monthly(year)
display(df[df['MM']==1])
print(df.shape)
print(df.info())

,YYYY,MM,PLANT,count,SUPP_QTY,count_cumsum,SUPP_QTY_cumsum,OEQI
0,2023,1,CP,0,156086.0,0,156086.0,0.000000
1,2023,1,DP,0,177674.0,0,177674.0,0.000000
2,2023,1,HP,0,160792.0,0,160792.0,0.000000
3,2023,1,IP,0,78782.0,0,78782.0,0.000000
4,2023,1,JP,0,406405.0,0,406405.0,0.000000
5,2023,1,KP,0,349665.0,0,349665.0,0.000000
6,2023,1,MP,5,378101.0,5,378101.0,13.223980
7,2023,1,OT,0,17200.0,0,17200.0,0.000000
8,2023,1,TP,4,168915.0,4,168915.0,23.680549
108,2024,1,CP,1,331480.0,1,331480.0,3.016773
109,2024,1,DP,0,214882.0,0,214882.0,0.000000
110,2024,1,HP,1,271348.0,1,271348.0,3.685304
111,2024,1,IP,2,256669.0,2,256669.0,7.792137
112,2024,1,JP,3,1262473.0,3,1262473.0,2.376288
113,2024,1,KP,2,580047.0,2,580047.0,3.447996
114,2024,1,MP,0,893132.0,0,893132.0,0.000000
115,2024,1,OT,0,30780.0,0,30780.0,0.000000
116,2024,1,TP,0,456055.0,0,456055.0,0.000000
216,2025,1,CP,0,247528.0,0,247528.0,0.000000
217,2025,1,DP,0,214613.0,0,214613.0,0.000000
218,2025,1,HP,1,182278.0,1,182278.0,5.486126
219,2025,1,IP,1,370431.0,1,370431.0,2.699558
220,2025,1,JP,0,970203.0,0,970203.0,0.000000
221,2025,1,KP,0,573127.0,0,573127.0,0.000000
222,2025,1,MP,3,1018147.0,3,1018147.0,2.946529
223,2025,1,OT,0,19190.0,0,19190.0,0.000000
224,2025,1,TP,0,339642.0,0,339642.0,0.000000

(324, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YYYY             324 non-null    int32
 1   MM               324 non-null    int32
 2   PLANT            324 non-null    object
 3   count            324 non-null    int64
 4   SUPP_QTY         261 non-null    float64
 5   count_cumsum     324 non-null    int64
 6   SUPP_QTY_cumsum  261 non-null    float64
 7   OEQI             261 non-null    float64
dtypes: float64(3), int32(2), int64(2), object(1)
memory usage: 17.8+ KB
None

In [112]:
df_app = df_oeapp.load_oeapp_df()
df_app = helper_pandas.standardize_columns_uppercase(df_app)
df_app = df_app[["PLANT", "M_CODE"]].drop_duplicates()
df_app

     PLANT   M_CODE
0       MP  1022601
1       MP  1023482
3       MP  1021310
4       MP  1023846
5       MP  1024622
...    ...      ...
1700    MP  1013117
1701    MP  1013116
1702    HP  3003448
1703    KP  3003748
1706    JP  1005903

[1424 rows x 2 columns]

In [120]:
global_yearly = repo.aggregate_oeqi_by_global_yearly(2025)
global_yearly

,YYYY,count,MTTC,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,SUPP_QTY,OEQI
0,2023,77,45.545455,21.987013,39.962963,20.173333,3.960526,49497960,1.555620
1,2024,66,21.166667,3.772727,3.4,12.848485,4.545455,49775252,1.325960
2,2025,23,15.217391,1.565217,1.0,11.478261,3.125,18199285,1.263786

In [164]:
df = repo.load_sellin_data_for_3_years(2023)
df

   PLANT  YYYY  MM  SUPP_QTY
0     CP  2023   2    140459
1     CP  2023   3    164134
2     CP  2023   4    138984
3     CP  2023   5    150084
4     CP  2023   6    165306
..   ...   ...  ..       ...
94    TP  2023   8    218940
95    TP  2023   9    197741
96    TP  2023  10    194754
97    TP  2023  11    199429
98    TP  2023  12    149069

[99 rows x 4 columns]

In [170]:
year = config.this_year
global_yearly = repo.aggregate_oeqi_by_global_yearly(year)
viz.draw_three_years_oeqi(global_yearly)
global_yearly

,YYYY,count,MTTC,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,SUPP_QTY,OEQI
0,2023,77,45.545455,21.987013,39.962963,20.173333,3.960526,23575083,3.266160
1,2024,66,21.166667,3.772727,3.4,12.848485,4.545455,24856265,2.655266
2,2025,23,15.217391,1.565217,1.0,11.478261,3.125,8876197,2.591200

In [169]:
df = repo.load_quality_issues_for_3_years(2025)
df =df[df['RETURN_YN'] == 'Y']
df

,OEQ GROUP,PLANT,STAGE,OEM,VEH,PJT,ISSUE_ETC,DESCRIPTION,CAUSE_OF_DEFECT,OWNER_ID,RESP_ID,OCC_DATE,REG_DATE,RETURN_YN,RTN_DATE,CTM_DATE,HK_FAULT_YN,COMP_DATE,STATUS,LOCATION,KPI,MARKET,SEQ,M_CODE,PNL_NM,TYPE,CAT,SUB_CAT,URL,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,MTTC,YYYY,MM
DOC_NO,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
QI-2024-00020,China OE Quality,CP,02,Ford,Mondeo,CD542 4DR,The shoulder of the tire is abnormal and lacks...,1. Location: Chang an Ford 2nd Line.\r\n2. Cha...,根据返回轮胎外观状态和制造过程追踪分析，确定为外物剐蹭造成损伤,81102484,80601183,2024-02-19,2024-02-19,Y,2024-02-29,2024-03-07,Y,2024-03-14,Complete,In-Line(OE),Include,ASIA(China),11B43FDD57785229E0633C071FCAB884,1027044,li junqiao,Apperance,Deform,Sidewall,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,8,5,5,10,2024,2
QI-2025-00070,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,FAW-VW reports that 29 unsold Magotan B8L new ...,Return analysis after tire replacement,None,81102484,81102484,2025-04-24,2025-04-24,Y,2025-05-05,NaT,None,NaT,On-going,Field,Include,ASIA(China),19665607d0f2a122eb6566587874e52b,1028484,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,7,4,<NA>,4,2025,4
QI-2025-00066,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,81102484,81102484,2025-04-16,2025-04-16,Y,2025-04-16,NaT,None,NaT,On-going,Field,Include,ASIA(China),1963da0906b1fbab73745d35101173d5,1028484,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4
QI-2025-00067,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,81102484,81102484,2025-04-16,2025-04-16,Y,2025-04-16,NaT,None,NaT,On-going,Field,Include,ASIA(China),1963daa2ccdfe833e6c19fd3f4f21ec9,1028485,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4
QI-2025-00040,China OE Quality,JP,02,VW,Tayron,A SUV PA,FAW-VW feedback that there have been 13 inci...,Analyze the returned tires\r\n,Considering the market sales environment and c...,81102484,81102484,2025-02-20,2025-02-21,Y,2025-02-21,2025-03-25,Y,2025-03-26,Complete,Field,Include,ASIA(China),2E9D460DE910290BE0633C071FCAD08C,1027058,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,1,0,22,1,24,2025,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
QI-2024-00137,NA OE Quality,TP,02,Honda,Pilot,PILOT,The flat tire is due to the small hole on the ...,Checked the manufacturing history according th...,1. According to inspection of tire and LOT tra...,21000075,21000075,2024-10-21,2024-10-24,Y,2024-10-23,2024-10-25,Y,2024-11-07,Complete,In-Line(OE),Include,North America,2529F4B9A61A25FDE0633C071FCA7FAE,1025366,None,Apperance,Assembly,Air Leak,http://egqms.hankooktech.com/OE_Quality_Issue/...,3,-1,2,9,14,2024,10
QI-2024-00081,NA OE Quality,TP,02,Renault-Nissan,Pathfinder,P42QR,Bulge in the Tire due to Insufficient Splice a...,Review which barcodes are suspect due to NG sp...,Based on the manufacturing history and dissect...,21000075,21000075,2024-05-31,2024-06-01,Y,2024-05-31,2024-06-17,Y,2024-06-18,Complete,In-Line(OE),Include,North America,19C9F8D904D6135BE0633C071FCAC3A3,1025265,None,Apperance,Visual,BPS(Dent/Bulge),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,-1,11,1,12,2024,6
QI-2025-00050,NA OE Quality,TP,02,Renault-Nissan,Frontier,H61P,Nissan found the sidewall issue during the mou...,Requested the barcode information and investig...,"Possible root cause : during vent drilling, a ...",21000075,21000075,2025-03-14,2025-03-15,Y,2025-03-14,2025-04-01,Y,2025-04-30,Complete,In-Line(OE),Include,North America,3054B2366662CF9FE0633C071FCA18E5,1026491,None,Apperance,Visual,Pin Hole ( Pin Hole,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,-1,12,21,33,2025,3
QI-2023-00033,China OE Quality,JP,02,BMW,X5,G18,1EA tire was found by inline staff with DM iss...,1. Required to return the tire\n2. Inline staf...,Bladder 차단제 도포 완료 후 오일 오염 방지 패드 제거 시 패드의 이물질이 ...,81704600,81704600,2023-03-03,2023-03-24,Y,2023-03-11,2023-03-13,Y,2023-03-14,Complete,In-Line(OE),Include,ASIA(China),F79E50874DB79725E0533C071FCA3100,1026224,None,Apperance,Visual,Dirty Mold(DM),http://egqms.hankooktech.com/OE_Quality_Issue/...,15,-1,0,1,16,2023,3
QI-2023-00115,China OE Quality,JP,02,VW,Tiguan,TIGUAN L PA,FMPA：轮胎下模胎侧表层异物\r\nForeign Material on the sid...,1. Reserve the tire and return\r\n2. Make 8D r...,气管更换作业时，老化的气管掉落在受台上，再生产时只确认模具和周边5S OK后恢复生产，导致轮...,81705340,81705340,2023-05-25,2023-10-25,Y,2023-10-25,2023-05-30,Y,2023-05-31,Complete,In-Line(OE),Include,ASIA(China),08835CC471DBA33CE0633C071FCA387E,1025505,None,Apperance,Visual,FM(Foreign Material),http://egqms.hankooktech.com/OE_Quality_Issue/...,109,0,-1,1,109,2023,10

In [173]:
df = repo.load_quality_issues_for_3_years(2025)
df = df[df['PLANT'] == 'JP']
df = df[df['YYYY'] == 2025]
df

,OEQ GROUP,PLANT,STAGE,OEM,VEH,PJT,ISSUE_ETC,DESCRIPTION,CAUSE_OF_DEFECT,OWNER_ID,RESP_ID,OCC_DATE,REG_DATE,RETURN_YN,RTN_DATE,CTM_DATE,HK_FAULT_YN,COMP_DATE,STATUS,LOCATION,KPI,MARKET,SEQ,M_CODE,PNL_NM,TYPE,CAT,SUB_CAT,URL,REG_PRD,RTN_PRD,CTM_PRD,COMP_PRD,MTTC,YYYY,MM
DOC_NO,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
QI-2025-00070,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,FAW-VW reports that 29 unsold Magotan B8L new ...,Return analysis after tire replacement,None,81102484,81102484,2025-04-24,2025-04-24,Y,2025-05-05,NaT,None,NaT,On-going,Field,Include,ASIA(China),19665607d0f2a122eb6566587874e52b,1028484,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,7,4,<NA>,4,2025,4
QI-2025-00066,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,81102484,81102484,2025-04-16,2025-04-16,Y,2025-04-16,NaT,None,NaT,On-going,Field,Include,ASIA(China),1963da0906b1fbab73745d35101173d5,1028484,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4
QI-2025-00067,China OE Quality,JP,02,VW,Passat,MAGOTAN B8L PA,"According to the notification from FAW-VW, the...",Goodwill implementation,None,81102484,81102484,2025-04-16,2025-04-16,Y,2025-04-16,NaT,None,NaT,On-going,Field,Include,ASIA(China),1963daa2ccdfe833e6c19fd3f4f21ec9,1028485,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4
QI-2025-00040,China OE Quality,JP,02,VW,Tayron,A SUV PA,FAW-VW feedback that there have been 13 inci...,Analyze the returned tires\r\n,Considering the market sales environment and c...,81102484,81102484,2025-02-20,2025-02-21,Y,2025-02-21,2025-03-25,Y,2025-03-26,Complete,Field,Include,ASIA(China),2E9D460DE910290BE0633C071FCAD08C,1027058,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,1,0,22,1,24,2025,2
QI-2025-00065,China OE Quality,JP,02,VW,Bora,BORA MQB PA,"According to the notification from FAW-VW, the...",Goodwill implementation.,None,81102484,81102484,2025-04-16,2025-04-16,Y,2025-04-16,NaT,None,NaT,On-going,Field,Include,ASIA(China),1963d990386b883dc67ffb54b4b31264,1027785,li junqiao,Apperance,Crack,Groove Crack,http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,17,<NA>,17,2025,4
QI-2025-00072,China OE Quality,JP,02,Leapmotor,C11,C11,"接技术服务T反馈,零跑售后投诉胎侧凹坑,邀请返回分析 Receiving feedback...",返回分析 Return to analysis,G/T着地或硫化下模具污染导致，硫化G/T投入前异物检查，设备停机再稼动模具清扫、卫生确认.,80021227,80025410,2025-05-05,2025-05-05,Y,2025-05-05,NaT,None,NaT,On-going,Field,Include,ASIA(China),1969f38768b079d8d3446d30c3528a14,1035082,Zhao Jianfeng,Apperance,Visual,FM(Foreign Material),http://egqms.hankooktech.com/OE_Quality_Issue/...,0,0,4,<NA>,4,2025,5